### ISSUE TITLE
Theo vs SSH certificates ?

### ISSUE THREAD

**Issue by champtar** [theoapp/theo-docs#2]
Hi @macno,

Before you started to work on Theo, have you considered / where you aware of the existence of ssh certificates ? (not to be confused with ssh keys)
https://github.com/Netflix/bless
https://code.fb.com/security/scalable-and-secure-access-with-ssh/
https://www.digitalocean.com/community/tutorials/how-to-create-an-ssh-ca-to-validate-hosts-and-clients-with-ubuntu

**Comment by macno** [comment]
Hi @champtar, thanks for your interest in Theo!
Yes, I know how ssh certificates works and I always avoid to adopt them because I never found a way to manage/maintain KRL efficiently. 
The usual workaround I saw it's to not use it at all, but this implies the use of a bastion (as described very well in FB link ) which uses another authentication method (for example LDAP). I don't know BLESS but from a first read of their docs it looks like they use the same ssh-jump-host approach, but I'll dig it deeper.
I think this solution is good for companies of a certain size, but it's too much of effort for a small/medium company.
The other problem I see with ssh certificates is the frequency on which accounts move from one team to another or - more in general - the need to change the principals in their certificates.
With Theo, the approach is different: all the grants are linked directly to the account (or group) and not to his/her keys. This way I think it's a lot simpler to manage the need of a small/medium company of changing roles/team/accounts frequently.

Anyway, introducing Theo does not mean you cannot use ssh certificates :)

I hope I answered your question, and if you have any other question or want to go deeper on the topic, I'll be more than happy to chat about it, just let me know!

**Comment by champtar** [comment]
Thanks !
My understanding is that nobody uses KRL, and they use short lived keys instead.

In my case the killer feature of SSH certificates is to be able to give access to new team member to "offline" servers (server at a clients in a dmz with no internet access but accessible via VPN)

For my current company I haven't found any SSH CA server that I liked so I ended up implementing a simple one in GO. With a one liner you POST your public key, login/password, your authenticated against our AD and you get all your principals from the AD groups.

In any case thanks for taking the time to share your project as opensource !!

**Comment by macno** [comment]
In your scenario I agree ssh certificates are the right solution because
you can revoke access disabling VPN account and you don’t have to deal with
KRL.

Out of curiosity, do your accounts execute the POST call each time they
have to connect to the customer?

**Comment by champtar** [comment]
Right now I sign the certs for 1 week, ideally I would set that to 12h, but I haven't transitioned everyone to SSH certs (I have to take care of my windows user base), and I don't want to slow down the adaption.

Another good thing about SSH certs is that the identity show up in the logs, so you quickly know who logged in.
